### ISSUE TITLE
Odd Whitespace

### ISSUE THREAD

**Issue by pigmonkey** [octobanana/fltrdr#8]
I'm seeing fltrdr insert odd whitespace in some files. So far it seems to be limited to URLs. For example, see the screenshot reading the README.md for this project:

![img-2019-02-19-203543](https://user-images.githubusercontent.com/502635/53066771-273bc000-3486-11e9-86dc-42c6a34d5553.png)

I am running v0.1.0 (18.02.2019).

**Comment by octobanana** [comment]
When the text is initially parsed, it splices words with a length longer then the minimum terminal width needed to display the program, which is set as 20. I decided to change it so that words now longer than the current screen width will just be cut off. Long words should now display normally when the full word can fit on the screen.

**Comment by pigmonkey** [comment]
That makes sense, and explains why I only noticed it with URLs. I have just tried the latest release and find the new behavior to be more intuitive.
